version: '{build}'
os: Windows Server 2012
environment:
  global:
    SCALAJS_VERSION: 1.7.1
  matrix:
    - SCALA_VERSION: 2.11.12
    - SCALA_VERSION: 2.12.15
    - SCALA_VERSION: 2.13.8
install:
  - cmd: choco install sbt --version 1.5.5 -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
build: off
test_script:
  - cmd: sbt ";clean;++%SCALA_VERSION%;set ThisBuild / scalaJSVersion := \"%SCALAJS_VERSION%\";cliPack"
cache:
  - C:\sbt
  - C:\Users\appveyor\.ivy2\cache
  - C:\Users\appveyor\.sbt
